{% set name = "spidermonkey" %}
{% set version = "91.10.0" %}
{% set majorversion = version.split('.')[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://releases.mozilla.org/pub/firefox/releases/{{ version }}esr/source/firefox-{{ version }}esr.source.tar.xz
    sha256: 825a8cb38bb5da9821ef87cc6de64af007cf0faef07c4ed0651283b56a0ee1bb
    patches:
      - 0000-fix-config.patch
      - 0001-va-args.patch
  - url: https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-4.0.1.exe  # [win]
    sha256: 7e22a2c44759f8eebdee3628c0fcd89515668571a7e06cc62a3ea9dc138b0390  # [win]

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('spidermonkey', max_pin='x') }}
  script_env:
    - MAJORVERSION={{ majorversion }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
    - m4  # [unix]
    - make
    - python >=3.7
    - perl >=5
    - pip
  host:
    - icu
    - zlib

outputs:
  - name: spidermonkey
    script: install_lib.sh
    test:
      commands:
        - test ! -f $PREFIX/bin/js{{ majorversion }}
        - test ! -f $PREFIX/bin/js{{ majorversion }}-config
        - test -f $PREFIX/lib/libmozjs-{{ majorversion }}${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/include/mozjs-{{ majorversion }}/js-config.h  # [unix]
        - test -f $PREFIX/include/mozjs-{{ majorversion }}/jsapi.h  # [unix]
  - name: spidermonkey-bin
    script: install_bin.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
        - python >=3.7
      host:
        - icu
        - zlib
    test:
      commands:
        - js{{ majorversion }} -e "console.log('hello')"
        - js{{ majorversion }}-config --version
        - test ! -f $PREFIX/lib/libmozjs-{{ majorversion }}${SHLIB_EXT}  # [unix]
        - test ! -f $PREFIX/include/mozjs-{{ majorversion }}/js-config.h  # [unix]
        - test ! -f $PREFIX/include/mozjs-{{ majorversion }}/jsapi.h  # [unix]

about:
  home: https://spidermonkey.dev/
  summary: Mozilla's JavaScript engine written in C/C++
  license: MPL-2.0
  license_family: MOZILLA
  license_file:
    - THIRDPARTY.yml
    - LICENSE
    - toolkit/content/license.html

extra:
  recipe-maintainers:
    - pepijndevos
    - zklaus
