{% set version = "115.4.0" %}
{% set majorversion = version.split('.')[0] %}

package:
  name: spidermonkey
  version: {{ version }}

source:
  url: https://releases.mozilla.org/pub/firefox/releases/{{ version }}esr/source/firefox-{{ version }}esr.source.tar.xz
  sha256: c31fdbf3a31b09f91b39fe45e084599a25f9644d3a615f263ac10189cd42ae59
  # patches:
  #   - 0000-fix-config.patch
  #   - 0001-va-args.patch

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage('spidermonkey', max_pin='x') }}
  script_env:
    - MAJORVERSION={{ majorversion }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - lld  # [osx]
    - m4
    - make
    - python >=3.7,<3.11
    - perl >=5
    - pip
    - pkg-config
  host:
    - zlib

outputs:
  - name: spidermonkey
    script: install_lib.sh
    test:
      commands:
        - test ! -f $PREFIX/bin/js{{ majorversion }}
        - test ! -f $PREFIX/bin/js{{ majorversion }}-config
        - test -f $PREFIX/lib/libmozjs-{{ majorversion }}${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/include/mozjs-{{ majorversion }}/js-config.h  # [unix]
        - test -f $PREFIX/include/mozjs-{{ majorversion }}/jsapi.h  # [unix]
  - name: spidermonkey-bin
    script: install_bin.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
        - python >=3.7
      host:
        - icu
        - zlib
    test:
      commands:
        - js{{ majorversion }} -e "console.log('hello')"
        - js{{ majorversion }}-config --version
        - test ! -f $PREFIX/lib/libmozjs-{{ majorversion }}${SHLIB_EXT}  # [unix]
        - test ! -f $PREFIX/include/mozjs-{{ majorversion }}/js-config.h  # [unix]
        - test ! -f $PREFIX/include/mozjs-{{ majorversion }}/jsapi.h  # [unix]

about:
  home: https://spidermonkey.dev
  summary: Mozilla's JavaScript engine written in C/C++
  license: MPL-2.0
  license_family: MOZILLA
  license_file:
    - THIRDPARTY.yml
    - LICENSE
    - toolkit/content/license.html
  dev_url: https://hg.mozilla.org/mozilla-central/file/tip/js
  doc_url: https://spidermonkey.dev/docs


extra:
  recipe-maintainers:
    - pepijndevos
    - zklaus
